<?php
/**
 * Payplug - https://www.payplug.com/
 * Copyright © Payplug. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Payplug\Payments\ViewModel\UrlProvider;

/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
/** @var Template $block */
/** @var UrlProvider $urlProvider */

$urlProvider = $viewModels->require(UrlProvider::class);
?>

<script>
    window.PAYPLUG_DOMAIN = '<?= $escaper->escapeJs($urlProvider->getPayplugSecureUrl()) ?>';

    (() => {
        window.addEventListener('checkout:payment:method-activate', (event) => {
            window.dispatchEvent(new Event('clear-messages'));
        });
    })();
</script>

<?php $hyvaCsp->registerInlineScript() ?>
