<?php
/**
 * Payplug - https://www.payplug.com/
 * Copyright © Payplug. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Payplug\PaymentsHyvaCheckout\Block\Standard as BlockStandard;
use Payplug\Payments\ViewModel\UrlProvider;

/** @var BlockStandard $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
/** @var UrlProvider $urlProvider */

$config = $block->getConfig();
$paymentConfig = $config['payment'];

$isIntegrated = false;
$isHostedFieldsActive = false;
$isOneClick = false;
$isPopup = false;
$isRedirected = false;
$hostedFieldsApiKeyId = '';
$hostedFieldsApiKey = '';
$localeCode = '';

if (isset($paymentConfig["payplug_payments_standard"])) {
    $isIntegrated = $paymentConfig["payplug_payments_standard"]["is_integrated"];
    $isHostedFieldsActive = $paymentConfig["payplug_payments_standard"]["is_hosted_fields_active"];
    $isOneClick = $paymentConfig["payplug_payments_standard"]["is_one_click"];
    $isPopup = $paymentConfig["payplug_payments_standard"]["is_embedded"];
    $isRedirected = !$isPopup && !$isIntegrated;
    $hostedFieldsApiKeyId = $paymentConfig["payplug_payments_standard"]["hosted_fields_api_key_id"];
    $hostedFieldsApiKey = $paymentConfig["payplug_payments_standard"]["hosted_fields_api_key"];
    $localeCode = $paymentConfig["payplug_payments_standard"]["locale_code"];
}

$urlProvider = $viewModels->require(UrlProvider::class);
$integratedPaymentUrl = $urlProvider->getPayplugIntegratedPaymentJsUrl() . '.js';
$hostedFieldsPaymentUrl = $urlProvider->getPayplugHostedFieldsJsUrl() . '.js';
?>

<script>
    (() => {
        hyvaCheckout.api.after(() => {
            let integratedPayment = {};
            const paymentOptions = {
                isIntegrated: <?= $isIntegrated ? 'true' : 'false' ?>,
                isHostedFieldsActive: <?= $isHostedFieldsActive ? 'true' : 'false' ?>,
                isOneClick: <?= $isOneClick ? 'true' : 'false' ?>,
                isPopup: <?= $isPopup ? 'true' : 'false' ?>,
                isRedirected: <?= $isRedirected ? 'true' : 'false' ?>,
                isSandbox: ''
            };

            function standardMethod() {
                return {
                    bindIntegratedPaymentFormToggle () {
                        const integratedPaymentForm = document.querySelector('#payplug-payment-form');
                        const radios = document.querySelectorAll('input[name="payment[payplug_payments_standard][customer_card_id]"]');
                        const otherCard = document.querySelector('#other-card');

                        radios.forEach(radio => {
                            radio.addEventListener('change', (event) => {
                                if (otherCard.checked) {
                                    paymentOptions.isOneClick = false;
                                    integratedPaymentForm.classList.remove('-hide');
                                } else {
                                    paymentOptions.isOneClick = true;
                                    integratedPaymentForm.classList.add('-hide');
                                }
                            });
                        });
                    },
                    fieldsErrorHandler () {
                        const container = document.getElementById('cardholder-container');
                        const errorContainer = container.nextElementSibling;
                        const invalidField = errorContainer.querySelector('.invalid-field');
                        const emptyField = errorContainer.querySelector('.empty-field');
                        const value = (document.getElementById('cardholder')?.value || '').trim();

                        container.classList.remove('error-empty', 'error-invalid');
                        invalidField.style.display = '';
                        emptyField.style.display = '';

                        if (value === '') {
                            container.classList.add('error-empty');
                            invalidField.style.display = 'none';
                            return false;
                        }

                        if (!/^[a-zA-ZÀ-ÿ]+(?:[ '\-][a-zA-ZÀ-ÿ]+)+$/.test(value)) {
                            container.classList.add('error-invalid');
                            emptyField.style.display = 'none';
                            return false;
                        }

                        return true;
                    },
                };
            }

            function integratedPaymentMethod() {
                return {
                    initialize: async function () {
                        function setIntegratedFormFields () {
                            const fieldStyle = {
                                default: {
                                    color: '#2B343D',
                                    fontFamily: 'Poppins, sans-serif',
                                    fontSize: '14px',
                                    textAlign: 'left',
                                    '::placeholder': {
                                        color: '#969a9f',
                                    },
                                    ':focus': {
                                        color: '#2B343D',
                                    }
                                },
                                invalid: {
                                    color: '#E91932'
                                }
                            };

                            const fields = [
                                {
                                    selector: '#cardholder-input-container',
                                    method: 'cardHolder',
                                    placeholder: '<?= $escaper->escapeJs(__('Name')) ?>'
                                },
                                {
                                    selector: '#pan-input-container',
                                    method: 'cardNumber',
                                    placeholder: '<?= $escaper->escapeJs(__('Card Number')) ?>'
                                },
                                {
                                    selector: '#cvv-input-container',
                                    method: 'cvv',
                                    placeholder: '<?= $escaper->escapeJs(__('CVV')) ?>'
                                },
                                {
                                    selector: '#exp-input-container',
                                    method: 'expiration',
                                    placeholder: '<?= $escaper->escapeJs(__('Exp Date')) ?>'
                                }
                            ];

                            fields.forEach(({ selector, method, placeholder }) => {
                                integratedPayment[method](
                                    document.querySelector(selector), 
                                    { ...fieldStyle, placeholder });
                            });
                        }

                        function setIntegratedPayment() {
                            integratedPayment = new Payplug.IntegratedPayment(paymentOptions.isSandbox);
                            integratedPayment.setDisplayMode3ds(Payplug.DisplayMode3ds.REDIRECT);
                            integratedPayment.getSupportedSchemes();
                            setIntegratedFormFields();
                        }

                        this.loadPayplugLib()
                            .then(() => {
                                if (paymentOptions.isIntegrated && !this.isInitialized()) {
                                    this.setFieldsError();
                                    setIntegratedPayment();
                                }
                            })
                            .catch(error => {
                                window.dispatchMessages([
                                    {
                                        type: 'error',
                                        text: '<?= $escaper->escapeJs(__('The Payplug library could not load correctly')) ?>'
                                    }
                                ], 2000);
                            });

                        if (paymentOptions.isOneClick) {
                            this.bindIntegratedPaymentFormToggle();
                        }
                    },
                    loadPayplugLib () {
                        return new Promise(resolve => {
                            const script = document.createElement('script');
                            script.type = 'text/javascript';
                            script.src =  '<?= $escaper->escapeJs($integratedPaymentUrl) ?>';
                            script.async = true;
                            script.onload = resolve;
                            document.head.appendChild(script);
                        });
                    },
                    isInitialized() {
                        return Object.keys(integratedPayment).length;
                    },
                    uninitialize: async function () {
                        integratedPayment = {};
                    },
                    setFieldsError() {
                        const inputs = document.querySelectorAll('#cardholder-input-container, #pan-input-container, #exp-input-container, #cvv-input-container');
                        const observer = new MutationObserver((mutations) => {
                            mutations.forEach(mutation => {
                                if (mutation.attributeName === 'class') {
                                    const input = mutation.target;
                                    const isValid = !input.classList.contains('integrated_payment_error');
                                    input.style.border = isValid ? '1px solid #d5d6d8' : '1px solid #FF0000';
                                    document.querySelector(`.error-container.${input.id} .invalid-field`).style.display = isValid ? 'none' : 'block';
                                }
                            });
                        });

                        const config = { attributes: true };
                        inputs.forEach(input => observer.observe(input, config));
                    },
                    validate: async function() {
                        const cancelUrl = BASE_URL + 'payplug_payments/payment/cancel';
                        const redirectUrl = BASE_URL + 'payplug_payments/payment/standard';
                        const returnUrl = BASE_URL + 'payplug_payments/payment/paymentReturn';
                        const activeMethod = document.querySelector('input[name="payment-method-option"]:checked')?.value || '';
                        const selectedInput = document.querySelector('input[name="payment[payplug_payments_standard][customer_card_id]"]:checked') || null;

                        if (activeMethod !== 'payplug_payments_standard') {
                            hyvaCheckout.main.getWireComponent().placeOrder();
                            return true;
                        }

                        if (paymentOptions.isOneClick) {
                            const cartId = selectedInput?.dataset?.cardId;
                            await Magewire.find('checkout.payment.method.payplug_payments_standard').call('setAditionalData', cartId);
                            hyvaCheckout.main.getWireComponent().placeOrder();
                            resolve();
                            return true;
                        } else {
                            if (paymentOptions.isIntegrated) {
                                const validateForm = () =>
                                    new Promise((resolve, reject) => {
                                        integratedPayment.onValidateForm(({ isFormValid }) => {
                                            isFormValid ? resolve() : reject();
                                        });
                                        integratedPayment.validateForm();
                                    });

                                hyvaCheckout.evaluation.registerExecutable('make:pay-plug:payment', async () => {
                                    try {
                                        magewire.plugins.loader.start();
                                        
                                        await validateForm();

                                        const response = await fetch(`${redirectUrl}?should_redirect=0&has_payment_form=1`);
                                        const { payment_id, error } = await response.json();

                                        if (error) throw new Error('Payment error');

                                        const saveCard = document.querySelector('#payplug_save_card')?.checked;

                                        return new Promise((resolve, reject) => {
                                            integratedPayment.pay(payment_id, 0, { save_card: saveCard });

                                            integratedPayment.onCompleted(() => {
                                                window.location.replace(returnUrl);
                                                resolve();
                                            });

                                            integratedPayment.onError?.(() => {
                                                window.location.replace(cancelUrl);
                                                reject();
                                            });
                                        });
                                    } catch (error) {
                                        window.location.replace(cancelUrl);
                                        throw error;
                                    }
                                });

                                <?php // Pre-validation ?>
                                validateForm()
                                    .then(() => hyvaCheckout.main.getWireComponent().placeOrder())
                                    .catch(console.error);

                                return;
                            }

                            if (paymentOptions.isRedirected) {
                                hyvaCheckout.main.getWireComponent().placeOrder();
                                resolve();
                                return true;
                            }

                            if (paymentOptions.isPopup) {
                                const closeIframe = Payplug.Form._closeIframe;

                                function redirectToCancelUrl() {
                                    window.location.replace(cancelUrl + '?form_key=${hyva.getFormKey()}');
                                };

                                Payplug.Form._closeIframe = () => {
                                    if (window.redirection_url) {
                                        return;
                                    }

                                    redirectToCancelUrl();
                                };

                                await hyvaCheckout.main.getWireComponent().placeOrder();

                                fetch(redirectUrl + '?should_redirect=0')
                                    .then(response => response.json())
                                    .then(({ is_paid, url }) => {
                                        if (is_paid) {
                                            window.location.replace(returnUrl);
                                        } else if (url) {
                                            Payplug.Form.showPayment(url, paymentOptions.isOneClick);
                                        } else {
                                            redirectToCancelUrl();
                                        }
                                    })
                                    .catch(console.error);
                            }
                        }
                    }
                }
            }

            let hostedFieldsApi = null;
            let hostedFieldsToken = null;
            let hostedFieldsSelectedBrand = null;

            function hostedFieldsPaymentMethod() {
                return {
                    hostedFieldsForm: null,
                    availableLanguages: ['fr', 'en', 'de', 'es', 'it', 'nl', 'zh', 'ru', 'pt', 'sk'],
                    apiKeyId: '<?= $escaper->escapeJs($hostedFieldsApiKeyId) ?>',
                    apiKey: '<?= $escaper->escapeJs($hostedFieldsApiKey) ?>',
                    locale: '<?= $escaper->escapeJs($localeCode) ?>',
                    inputStyles: {
                        input: {
                            "font-size": "14px",
                            "line-height": "38px",
                        },
                        '::placeholder': {
                            'letter-spacing': '0.1em'
                        },
                        ':invalid':  {
                            "color": "red"
                        }
                    },
                    initialize: async function () {
                        this.loadHostedFieldsLib()
                            .then(() => {
                                this.initPaymentForm();
                            })
                            .catch(error => {
                                window.dispatchMessages([
                                    {
                                        type: 'error',
                                        text: '<?= $escaper->escapeJs(__('Dalenys library could not load correctly')) ?>'
                                    }
                                ], 2000);
                            });
                    },
                    loadHostedFieldsLib () {
                        return new Promise(resolve => {
                            const script = document.createElement('script');
                            script.type = 'text/javascript';
                            script.src =  '<?= $escaper->escapeJs($hostedFieldsPaymentUrl) ?>';
                            script.async = true;
                            script.onload = resolve;
                            document.head.appendChild(script);
                        });
                    },
                    initPaymentForm () {
                        if (hostedFieldsApi !== null) {
                            return false;
                        }

                        const lang = this.locale.split('_')[0];

                        if (!this.availableLanguages.includes(lang)) {
                            lang = 'fr';
                        }

                        const hostedFieldsConfig = {
                            key: {
                                id: this.apiKeyId,
                                value: this.apiKey,
                            },
                            theme: {
                                mode: 'light'
                            },
                            fields: {
                                brand: {
                                    id: 'brand-container',
                                    version: 2,
                                    useInlineSelection: false,
                                    isCbPreferredNetwork: true
                                },
                                card: {
                                    id: 'pan-input-container',
                                    placeholder: '•••• •••• •••• ••••',
                                    enableAutospacing: true,
                                    style: this.inputStyles,
                                },
                                expiry: {
                                    id: 'exp-input-container',
                                    placeholder: '<?= $escaper->escapeJs(__('MM/YY')) ?>',
                                    style: this.inputStyles
                                },
                                cryptogram: {
                                    id: 'cvv-input-container',
                                    placeholder: 'CVV',
                                    style: this.inputStyles
                                },
                            },
                            location: lang,
                        };

                        hostedFieldsApi = dalenys.hostedFields(hostedFieldsConfig);
                        hostedFieldsApi.load();

                        ['input', 'blur'].forEach(event => {
                            document.getElementById('cardholder').addEventListener(event, this.validateCardholder);
                        });

                        return true;
                    },
                    validateCardholder () {
                        const container = document.getElementById('cardholder-input-container');
                        const errorContainer = container.nextElementSibling;
                        const invalidField = errorContainer.querySelector('.invalid-field');
                        const emptyField = errorContainer.querySelector('.empty-field');
                        const value = (document.getElementById('cardholder')?.value || '').trim();

                        container.classList.remove('error-empty', 'error-invalid');
                        invalidField.style.display = '';
                        emptyField.style.display = '';

                        if (value === '') {
                            container.classList.add('error-empty');
                            invalidField.style.display = 'none';
                            return false;
                        }

                        if (!/^[a-zA-ZÀ-ÿ]+(?:[ '\-][a-zA-ZÀ-ÿ]+)+$/.test(value)) {
                            container.classList.add('error-invalid');
                            emptyField.style.display = 'none';
                            return false;
                        }

                        return true;
                    },
                    validate: async function() {
                        const cancelUrl = BASE_URL + 'payplug_payments/payment/cancel';
                        const returnUrl = BASE_URL + 'payplug_payments/payment/paymentReturn';
                        const redirectUrl = BASE_URL + 'payplug_payments/payment/standard';

                        await new Promise((resolve, reject) => {
                            hostedFieldsApi.createToken(function (result) {
                                magewire.plugins.loader.stop();

                                if (result.execCode !== '0000') {
                                    window.dispatchMessages([
                                        {
                                            type: 'error',
                                            text: '<?= $escaper->escapeJs(__('The transaction was aborted and your card has not been charged')) ?>'
                                        }
                                    ], 2000);
                                    reject(new Error('Token creation failed'));
                                    return;
                                }

                                hostedFieldsToken = result.hfToken;
                                hostedFieldsSelectedBrand = result.selectedBrand;
                                resolve();
                            });
                        });

                        hyvaCheckout.evaluation.registerExecutable('make:pay-plug:payment', async () => {
                            try {
                                magewire.plugins.loader.start();

                                const response = await fetch(`${redirectUrl}?should_redirect=0&has_payment_form=1`);
                                const { payment_id, error } = await response.json();

                                if (error) throw new Error('Payment error');

                                return new Promise((resolve, reject) => {
                                    if (response.error === true) {
                                        alert(response.message);
                                        window.location.replace(cancelUrl);
                                        return;
                                    }

                                    if (!response.payment_id) {
                                        window.location.replace(returnUrl);
                                        return;
                                    }

                                    // TODO afterStandardSuccess() transpil
                                });
                            } catch (error) {
                                window.location.replace(cancelUrl);
                                throw error;
                            }
                        });

                        const selectedInput = document.querySelector('input[name="payment[payplug_payments_standard][customer_card_id]"]:checked') || null;
                        const cartId = selectedInput?.dataset?.cardId;
                        const saveCard = (document.querySelector('#payplug_save_card')?.checked ?? false) && paymentOptions.isOneClick;
                        const cardHolder = document.getElementById('cardholder')?.value || '';

                        await Magewire.find('checkout.payment.method.payplug_payments_standard').call(
                            'setHostedFieldsAdditionalData',
                            hostedFieldsToken,
                            hostedFieldsSelectedBrand,
                            saveCard,
                            cardHolder
                        );

                        hyvaCheckout.main.getWireComponent().placeOrder();
                        return true;
                    }
                }
            }

            hyvaCheckout.payment.registerMethod({
                code: 'payplug_payments_standard',
                method: {
                    ...standardMethod(),
                    <?php if ($isHostedFieldsActive): ?>
                    ...hostedFieldsPaymentMethod()
                    <?php else: ?>
                    ...integratedPaymentMethod()
                    <?php endif; ?>
                }
            });
        });
    })();
</script>

<?php $hyvaCsp->registerInlineScript() ?>

<script>
    function integratedStandardPayment() {
        return Object.assign(
            { currentCard: '' },
            {
                ['handleInputChange'](event) { return this.currentCard = this.$el.value },
                ['visaCardClass']() { return this.currentCard === 'visa' ? 'inline' : 'hidden' },
                ['visaCardDarkClass']() { return this.currentCard === 'visa' ? 'hidden' : 'inline' },
                ['masterCardClass']() { return this.currentCard === 'mastercard' ? 'inline' : 'hidden' },
                ['masterCardDarkClass']() { return this.currentCard === 'mastercard' ? 'hidden' : 'inline' },
                ['cbCardClass']() { return this.currentCard === 'cb' ? 'inline' : 'hidden' },
                ['cbCardDarkClass']() { return this.currentCard === 'cb' ? 'hidden' : 'inline' },
            }
        )
    }

    window.addEventListener('alpine:init', () => {
        Alpine.data('integratedStandardPayment', integratedStandardPayment);
    }, {once: true});
</script>

<?php $hyvaCsp->registerInlineScript() ?>
