<?php
/**
 * Payplug - https://www.payplug.com/
 * Copyright © Payplug. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Payplug\PaymentsHyvaCheckout\Block\Standard as BlockStandard;

/** @var BlockStandard $block */

$config = $block->getConfig();
$paymentConfig = $config['payment'];
$isHostedFieldsActive = $paymentConfig['payplug_payments_standard']['is_hosted_fields_active'] ?? false;
?>

<?php if ($isHostedFieldsActive): ?>
    <?= $block->getChildHtml('standard_hosted_fields') ?>
<?php else: ?>
    <?= $block->getChildHtml('standard_integrated') ?>
<?php endif; ?>

<script>
    function standardPayment() {
        return Object.assign(
            { currentCard: '' },
            {
                ['handleInputChange'](event) { return this.currentCard = this.$el.value },
                ['visaCardClass']() { return this.currentCard === 'visa' ? 'inline' : 'hidden' },
                ['visaCardDarkClass']() { return this.currentCard === 'visa' ? 'hidden' : 'inline' },
                ['masterCardClass']() { return this.currentCard === 'mastercard' ? 'inline' : 'hidden' },
                ['masterCardDarkClass']() { return this.currentCard === 'mastercard' ? 'hidden' : 'inline' },
                ['cbCardClass']() { return this.currentCard === 'cb' ? 'inline' : 'hidden' },
                ['cbCardDarkClass']() { return this.currentCard === 'cb' ? 'hidden' : 'inline' },
            }
        )
    }

    window.addEventListener('alpine:init', () => {
        Alpine.data('standardPayment', standardPayment);
    }, {once: true});
</script>

<?php $hyvaCsp->registerInlineScript() ?>
